/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as UnitsRouteImport } from './routes/units'
import { Route as TransferStockRouteImport } from './routes/transfer-stock'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StockAdjustmentRouteImport } from './routes/stock-adjustment'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PosRouteImport } from './routes/pos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitsRoute = UnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferStockRoute = TransferStockRouteImport.update({
  id: '/transfer-stock',
  path: '/transfer-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAdjustmentRoute = StockAdjustmentRouteImport.update({
  id: '/stock-adjustment',
  path: '/stock-adjustment',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/suppliers': typeof SuppliersRoute
  '/transfer-stock': typeof TransferStockRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/suppliers': typeof SuppliersRoute
  '/transfer-stock': typeof TransferStockRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRoute
  '/categories': typeof CategoriesRoute
  '/customers': typeof CustomersRoute
  '/finance': typeof FinanceRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/pos': typeof PosRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/purchases': typeof PurchasesRoute
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRoute
  '/settings': typeof SettingsRoute
  '/stock-adjustment': typeof StockAdjustmentRoute
  '/suppliers': typeof SuppliersRoute
  '/transfer-stock': typeof TransferStockRoute
  '/units': typeof UnitsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/categories'
    | '/customers'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-adjustment'
    | '/suppliers'
    | '/transfer-stock'
    | '/units'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brands'
    | '/categories'
    | '/customers'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-adjustment'
    | '/suppliers'
    | '/transfer-stock'
    | '/units'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/categories'
    | '/customers'
    | '/finance'
    | '/inventory'
    | '/login'
    | '/pos'
    | '/products'
    | '/profile'
    | '/purchases'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/stock-adjustment'
    | '/suppliers'
    | '/transfer-stock'
    | '/units'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRoute: typeof BrandsRoute
  CategoriesRoute: typeof CategoriesRoute
  CustomersRoute: typeof CustomersRoute
  FinanceRoute: typeof FinanceRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  PosRoute: typeof PosRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  PurchasesRoute: typeof PurchasesRoute
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRoute
  SettingsRoute: typeof SettingsRoute
  StockAdjustmentRoute: typeof StockAdjustmentRoute
  SuppliersRoute: typeof SuppliersRoute
  TransferStockRoute: typeof TransferStockRoute
  UnitsRoute: typeof UnitsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transfer-stock': {
      id: '/transfer-stock'
      path: '/transfer-stock'
      fullPath: '/transfer-stock'
      preLoaderRoute: typeof TransferStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-adjustment': {
      id: '/stock-adjustment'
      path: '/stock-adjustment'
      fullPath: '/stock-adjustment'
      preLoaderRoute: typeof StockAdjustmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRoute: BrandsRoute,
  CategoriesRoute: CategoriesRoute,
  CustomersRoute: CustomersRoute,
  FinanceRoute: FinanceRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  PosRoute: PosRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  PurchasesRoute: PurchasesRoute,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRoute,
  SettingsRoute: SettingsRoute,
  StockAdjustmentRoute: StockAdjustmentRoute,
  SuppliersRoute: SuppliersRoute,
  TransferStockRoute: TransferStockRoute,
  UnitsRoute: UnitsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
